return {
    {
        'nvim-treesitter/nvim-treesitter',
        build = ':TSUpdate',
        opts = {
            ensure_installed = {
                "astro",
                "bash",
                "c",
                "cmake",
                -- "comment", -- comments are slowing down TS bigtime, so disable for now
                "cpp",
                "css",
                "diff",
                "fish",
                "gitignore",
                "go",
                "graphql",
                "help",
                "html",
                "http",
                "java",
                "javascript",
                "jsdoc",
                "jsonc",
                "latex",
                "lua",
                "luap",
                "markdown",
                "markdown_inline",
                "meson",
                "ninja",
                "nix",
                "norg",
                "org",
                "php",
                "python",
                "query",
                "regex",
                "rust",
                "scss",
                "sql",
                "svelte",
                "teal",
                "toml",
                "tsx",
                "typescript",
                "vhs",
                "vim",
                "vue",
                "wgsl",
                "yaml",
                "json",
            },
            matchup = {
                enable = true,
            },
            highlight = { enable = true },
            query_linter = {
                enable = true,
                use_virtual_text = true,
                lint_events = { "BufWrite", "CursorHold" },
            },
        },
    },

    {
        "nvim-treesitter/nvim-treesitter-textobjects",
        dependencies = { "nvim-treesitter/nvim-treesitter" },
    },

    {
        "nvim-treesitter/nvim-treesitter-context",
        dependencies = { "nvim-treesitter/nvim-treesitter" },
        event = "BufReadPre",
        config = true,
    },
}
